name: dnd_html5
version: 0.3.6
authors:
 - Marco Jakob <majakob@gmx.ch>
 - Vittorio Ballestra <vittorio.ballestra@gmail.com>
description: Drag and Drop for Dart web apps with mouse and touch support.
homepage: http://code.makery.ch/library/dart-drag-and-drop/
documentation: http://www.dartdocs.org/documentation/dnd/latest/
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  browser: '>=0.10.0 <0.11.0'
  html5: ^0.1.4
  polymerize: ^0.9.3
#dependency_overrides:
#  html5:
#    path: ../html_lib
transformers:
  - polymerize
